# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/joe/Ultra96-PYNQ/Ultra96/sensors96b/sensors96b/sensors96b.srcs/sources_1/bd/sensors96b/ip/sensors96b_xbar_3/sensors96b_xbar_3.xci
# IP: The module: 'sensors96b_xbar_3' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/joe/Ultra96-PYNQ/Ultra96/sensors96b/sensors96b/sensors96b.srcs/sources_1/bd/sensors96b/ip/sensors96b_xbar_3/sensors96b_xbar_3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sensors96b_xbar_3'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/joe/Ultra96-PYNQ/Ultra96/sensors96b/sensors96b/sensors96b.srcs/sources_1/bd/sensors96b/ip/sensors96b_xbar_3/sensors96b_xbar_3.xci
# IP: The module: 'sensors96b_xbar_3' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/joe/Ultra96-PYNQ/Ultra96/sensors96b/sensors96b/sensors96b.srcs/sources_1/bd/sensors96b/ip/sensors96b_xbar_3/sensors96b_xbar_3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sensors96b_xbar_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
