# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/constraints/sensors96b.xdc

# Block Designs: bd/sensors96b/sensors96b.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sensors96b || ORIG_REF_NAME==sensors96b} -quiet] -quiet

# IP: bd/sensors96b/ip/sensors96b_axi_uart16550_0_0/sensors96b_axi_uart16550_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sensors96b_axi_uart16550_0_0 || ORIG_REF_NAME==sensors96b_axi_uart16550_0_0} -quiet] -quiet

# IP: bd/sensors96b/ip/sensors96b_zynq_ultra_ps_e_0_0/sensors96b_zynq_ultra_ps_e_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sensors96b_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==sensors96b_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/sensors96b/ip/sensors96b_xlconcat_0_0/sensors96b_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sensors96b_xlconcat_0_0 || ORIG_REF_NAME==sensors96b_xlconcat_0_0} -quiet] -quiet

# IP: bd/sensors96b/ip/sensors96b_vadd_0_0/sensors96b_vadd_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sensors96b_vadd_0_0 || ORIG_REF_NAME==sensors96b_vadd_0_0} -quiet] -quiet

# IP: bd/sensors96b/ip/sensors96b_ps8_0_axi_periph_3/sensors96b_ps8_0_axi_periph_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sensors96b_ps8_0_axi_periph_3 || ORIG_REF_NAME==sensors96b_ps8_0_axi_periph_3} -quiet] -quiet

# IP: bd/sensors96b/ip/sensors96b_rst_ps8_0_99M_2/sensors96b_rst_ps8_0_99M_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sensors96b_rst_ps8_0_99M_2 || ORIG_REF_NAME==sensors96b_rst_ps8_0_99M_2} -quiet] -quiet

# IP: bd/sensors96b/ip/sensors96b_axi_smc_2/sensors96b_axi_smc_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sensors96b_axi_smc_2 || ORIG_REF_NAME==sensors96b_axi_smc_2} -quiet] -quiet

# IP: bd/sensors96b/ip/sensors96b_xbar_3/sensors96b_xbar_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sensors96b_xbar_3 || ORIG_REF_NAME==sensors96b_xbar_3} -quiet] -quiet

# IP: bd/sensors96b/ip/sensors96b_auto_pc_0/sensors96b_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sensors96b_auto_pc_0 || ORIG_REF_NAME==sensors96b_auto_pc_0} -quiet] -quiet

# XDC: bd/sensors96b/sensors96b_ooc.xdc
