# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/joe/Ultra96-PYNQ/Ultra96/sensors96b/sensors96b/sensors96b.srcs/sources_1/bd/sensors96b/ip/sensors96b_axi_smc_2/sensors96b_axi_smc_2.xci
# IP: The module: 'sensors96b_axi_smc_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/joe/Ultra96-PYNQ/Ultra96/sensors96b/sensors96b/sensors96b.srcs/sources_1/bd/sensors96b/ip/sensors96b_axi_smc_2/bd_0/bd_04cc.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/joe/Ultra96-PYNQ/Ultra96/sensors96b/sensors96b/sensors96b.srcs/sources_1/bd/sensors96b/ip/sensors96b_axi_smc_2/bd_0/ip/ip_5/bd_04cc_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/joe/Ultra96-PYNQ/Ultra96/sensors96b/sensors96b/sensors96b.srcs/sources_1/bd/sensors96b/ip/sensors96b_axi_smc_2/bd_0/ip/ip_11/bd_04cc_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/joe/Ultra96-PYNQ/Ultra96/sensors96b/sensors96b/sensors96b.srcs/sources_1/bd/sensors96b/ip/sensors96b_axi_smc_2/bd_0/ip/ip_12/bd_04cc_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/joe/Ultra96-PYNQ/Ultra96/sensors96b/sensors96b/sensors96b.srcs/sources_1/bd/sensors96b/ip/sensors96b_axi_smc_2/bd_0/ip/ip_6/bd_04cc_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/joe/Ultra96-PYNQ/Ultra96/sensors96b/sensors96b/sensors96b.srcs/sources_1/bd/sensors96b/ip/sensors96b_axi_smc_2/bd_0/ip/ip_7/bd_04cc_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/joe/Ultra96-PYNQ/Ultra96/sensors96b/sensors96b/sensors96b.srcs/sources_1/bd/sensors96b/ip/sensors96b_axi_smc_2/bd_0/ip/ip_8/bd_04cc_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/joe/Ultra96-PYNQ/Ultra96/sensors96b/sensors96b/sensors96b.srcs/sources_1/bd/sensors96b/ip/sensors96b_axi_smc_2/bd_0/ip/ip_9/bd_04cc_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/joe/Ultra96-PYNQ/Ultra96/sensors96b/sensors96b/sensors96b.srcs/sources_1/bd/sensors96b/ip/sensors96b_axi_smc_2/bd_0/ip/ip_10/bd_04cc_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/joe/Ultra96-PYNQ/Ultra96/sensors96b/sensors96b/sensors96b.srcs/sources_1/bd/sensors96b/ip/sensors96b_axi_smc_2/bd_0/ip/ip_2/bd_04cc_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/joe/Ultra96-PYNQ/Ultra96/sensors96b/sensors96b/sensors96b.srcs/sources_1/bd/sensors96b/ip/sensors96b_axi_smc_2/bd_0/ip/ip_3/bd_04cc_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/joe/Ultra96-PYNQ/Ultra96/sensors96b/sensors96b/sensors96b.srcs/sources_1/bd/sensors96b/ip/sensors96b_axi_smc_2/bd_0/ip/ip_4/bd_04cc_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/joe/Ultra96-PYNQ/Ultra96/sensors96b/sensors96b/sensors96b.srcs/sources_1/bd/sensors96b/ip/sensors96b_axi_smc_2/bd_0/ip/ip_0/bd_04cc_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/joe/Ultra96-PYNQ/Ultra96/sensors96b/sensors96b/sensors96b.srcs/sources_1/bd/sensors96b/ip/sensors96b_axi_smc_2/bd_0/ip/ip_1/bd_04cc_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: /home/joe/Ultra96-PYNQ/Ultra96/sensors96b/sensors96b/sensors96b.srcs/sources_1/bd/sensors96b/ip/sensors96b_axi_smc_2/bd_0/ip/ip_5/bd_04cc_s00a2s_0_ooc.xdc

# XDC: /home/joe/Ultra96-PYNQ/Ultra96/sensors96b/sensors96b/sensors96b.srcs/sources_1/bd/sensors96b/ip/sensors96b_axi_smc_2/bd_0/ip/ip_11/bd_04cc_m00s2a_0_ooc.xdc

# XDC: /home/joe/Ultra96-PYNQ/Ultra96/sensors96b/sensors96b/sensors96b.srcs/sources_1/bd/sensors96b/ip/sensors96b_axi_smc_2/bd_0/ip/ip_6/bd_04cc_sarn_0_ooc.xdc

# XDC: /home/joe/Ultra96-PYNQ/Ultra96/sensors96b/sensors96b/sensors96b.srcs/sources_1/bd/sensors96b/ip/sensors96b_axi_smc_2/bd_0/ip/ip_7/bd_04cc_srn_0_ooc.xdc

# XDC: /home/joe/Ultra96-PYNQ/Ultra96/sensors96b/sensors96b/sensors96b.srcs/sources_1/bd/sensors96b/ip/sensors96b_axi_smc_2/bd_0/ip/ip_8/bd_04cc_sawn_0_ooc.xdc

# XDC: /home/joe/Ultra96-PYNQ/Ultra96/sensors96b/sensors96b/sensors96b.srcs/sources_1/bd/sensors96b/ip/sensors96b_axi_smc_2/bd_0/ip/ip_9/bd_04cc_swn_0_ooc.xdc

# XDC: /home/joe/Ultra96-PYNQ/Ultra96/sensors96b/sensors96b/sensors96b.srcs/sources_1/bd/sensors96b/ip/sensors96b_axi_smc_2/bd_0/ip/ip_10/bd_04cc_sbn_0_ooc.xdc

# XDC: /home/joe/Ultra96-PYNQ/Ultra96/sensors96b/sensors96b/sensors96b.srcs/sources_1/bd/sensors96b/ip/sensors96b_axi_smc_2/bd_0/ip/ip_1/bd_04cc_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/joe/Ultra96-PYNQ/Ultra96/sensors96b/sensors96b/sensors96b.srcs/sources_1/bd/sensors96b/ip/sensors96b_axi_smc_2/bd_0/ip/ip_1/bd_04cc_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/joe/Ultra96-PYNQ/Ultra96/sensors96b/sensors96b/sensors96b.srcs/sources_1/bd/sensors96b/ip/sensors96b_axi_smc_2/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sensors96b_axi_smc_2'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/joe/Ultra96-PYNQ/Ultra96/sensors96b/sensors96b/sensors96b.srcs/sources_1/bd/sensors96b/ip/sensors96b_axi_smc_2/sensors96b_axi_smc_2.xci
# IP: The module: 'sensors96b_axi_smc_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/joe/Ultra96-PYNQ/Ultra96/sensors96b/sensors96b/sensors96b.srcs/sources_1/bd/sensors96b/ip/sensors96b_axi_smc_2/bd_0/bd_04cc.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/joe/Ultra96-PYNQ/Ultra96/sensors96b/sensors96b/sensors96b.srcs/sources_1/bd/sensors96b/ip/sensors96b_axi_smc_2/bd_0/ip/ip_5/bd_04cc_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/joe/Ultra96-PYNQ/Ultra96/sensors96b/sensors96b/sensors96b.srcs/sources_1/bd/sensors96b/ip/sensors96b_axi_smc_2/bd_0/ip/ip_11/bd_04cc_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/joe/Ultra96-PYNQ/Ultra96/sensors96b/sensors96b/sensors96b.srcs/sources_1/bd/sensors96b/ip/sensors96b_axi_smc_2/bd_0/ip/ip_12/bd_04cc_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/joe/Ultra96-PYNQ/Ultra96/sensors96b/sensors96b/sensors96b.srcs/sources_1/bd/sensors96b/ip/sensors96b_axi_smc_2/bd_0/ip/ip_6/bd_04cc_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/joe/Ultra96-PYNQ/Ultra96/sensors96b/sensors96b/sensors96b.srcs/sources_1/bd/sensors96b/ip/sensors96b_axi_smc_2/bd_0/ip/ip_7/bd_04cc_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/joe/Ultra96-PYNQ/Ultra96/sensors96b/sensors96b/sensors96b.srcs/sources_1/bd/sensors96b/ip/sensors96b_axi_smc_2/bd_0/ip/ip_8/bd_04cc_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/joe/Ultra96-PYNQ/Ultra96/sensors96b/sensors96b/sensors96b.srcs/sources_1/bd/sensors96b/ip/sensors96b_axi_smc_2/bd_0/ip/ip_9/bd_04cc_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/joe/Ultra96-PYNQ/Ultra96/sensors96b/sensors96b/sensors96b.srcs/sources_1/bd/sensors96b/ip/sensors96b_axi_smc_2/bd_0/ip/ip_10/bd_04cc_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/joe/Ultra96-PYNQ/Ultra96/sensors96b/sensors96b/sensors96b.srcs/sources_1/bd/sensors96b/ip/sensors96b_axi_smc_2/bd_0/ip/ip_2/bd_04cc_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/joe/Ultra96-PYNQ/Ultra96/sensors96b/sensors96b/sensors96b.srcs/sources_1/bd/sensors96b/ip/sensors96b_axi_smc_2/bd_0/ip/ip_3/bd_04cc_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/joe/Ultra96-PYNQ/Ultra96/sensors96b/sensors96b/sensors96b.srcs/sources_1/bd/sensors96b/ip/sensors96b_axi_smc_2/bd_0/ip/ip_4/bd_04cc_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/joe/Ultra96-PYNQ/Ultra96/sensors96b/sensors96b/sensors96b.srcs/sources_1/bd/sensors96b/ip/sensors96b_axi_smc_2/bd_0/ip/ip_0/bd_04cc_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/joe/Ultra96-PYNQ/Ultra96/sensors96b/sensors96b/sensors96b.srcs/sources_1/bd/sensors96b/ip/sensors96b_axi_smc_2/bd_0/ip/ip_1/bd_04cc_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: /home/joe/Ultra96-PYNQ/Ultra96/sensors96b/sensors96b/sensors96b.srcs/sources_1/bd/sensors96b/ip/sensors96b_axi_smc_2/bd_0/ip/ip_5/bd_04cc_s00a2s_0_ooc.xdc

# XDC: /home/joe/Ultra96-PYNQ/Ultra96/sensors96b/sensors96b/sensors96b.srcs/sources_1/bd/sensors96b/ip/sensors96b_axi_smc_2/bd_0/ip/ip_11/bd_04cc_m00s2a_0_ooc.xdc

# XDC: /home/joe/Ultra96-PYNQ/Ultra96/sensors96b/sensors96b/sensors96b.srcs/sources_1/bd/sensors96b/ip/sensors96b_axi_smc_2/bd_0/ip/ip_6/bd_04cc_sarn_0_ooc.xdc

# XDC: /home/joe/Ultra96-PYNQ/Ultra96/sensors96b/sensors96b/sensors96b.srcs/sources_1/bd/sensors96b/ip/sensors96b_axi_smc_2/bd_0/ip/ip_7/bd_04cc_srn_0_ooc.xdc

# XDC: /home/joe/Ultra96-PYNQ/Ultra96/sensors96b/sensors96b/sensors96b.srcs/sources_1/bd/sensors96b/ip/sensors96b_axi_smc_2/bd_0/ip/ip_8/bd_04cc_sawn_0_ooc.xdc

# XDC: /home/joe/Ultra96-PYNQ/Ultra96/sensors96b/sensors96b/sensors96b.srcs/sources_1/bd/sensors96b/ip/sensors96b_axi_smc_2/bd_0/ip/ip_9/bd_04cc_swn_0_ooc.xdc

# XDC: /home/joe/Ultra96-PYNQ/Ultra96/sensors96b/sensors96b/sensors96b.srcs/sources_1/bd/sensors96b/ip/sensors96b_axi_smc_2/bd_0/ip/ip_10/bd_04cc_sbn_0_ooc.xdc

# XDC: /home/joe/Ultra96-PYNQ/Ultra96/sensors96b/sensors96b/sensors96b.srcs/sources_1/bd/sensors96b/ip/sensors96b_axi_smc_2/bd_0/ip/ip_1/bd_04cc_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/joe/Ultra96-PYNQ/Ultra96/sensors96b/sensors96b/sensors96b.srcs/sources_1/bd/sensors96b/ip/sensors96b_axi_smc_2/bd_0/ip/ip_1/bd_04cc_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/joe/Ultra96-PYNQ/Ultra96/sensors96b/sensors96b/sensors96b.srcs/sources_1/bd/sensors96b/ip/sensors96b_axi_smc_2/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sensors96b_axi_smc_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
